# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      page:
        description: 'Select a single page to test (ignored if classes or testNGSuite is set)'
        required: true
        default: 'All'
        type: choice
        options:
          - All
          - Tasks.TestTask1
          - Tasks.TestTask2
          - Tasks.TestTask3
          - Tasks.TestTask4
          - Tasks.TestTask5

      classes:
        description: 'Optional: Comma-separated list of test classes to run (e.g., Tasks.TestTask1,Tasks.TestTask2)'
        required: false

      testNGSuite:
        description: 'Optional: Run a specific TestNG XML file (e.g., testngThreadLocal.xml)'
        required: false

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  id-token: write
  security-events: write

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run selected tests
        run: |
          if [ -n "${{ github.event.inputs.testNGSuite }}" ]; then
            echo "Running TestNG suite: ${{ github.event.inputs.testNGSuite }}"
            mvn clean test -DtestNGSuite=${{ github.event.inputs.testNGSuite }}
          elif [ -n "${{ github.event.inputs.classes }}" ]; then
            echo "Running multiple classes: ${{ github.event.inputs.classes }}"
            mvn clean test -Dtest=${{ github.event.inputs.classes }}
          elif [ "${{ github.event.inputs.page }}" = "All" ]; then
            echo "Running all tests"
            mvn clean test
          else
            echo "Running single page: ${{ github.event.inputs.page }}"
            mvn clean test -Dtest=${{ github.event.inputs.page }}
        shell: bash

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4
